# Generated by Django 5.0.14 on 2026-07-13 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clergy", "0002_initial"),
        ("requests_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("escalation_level", models.PositiveIntegerField(default=0)),
                ("escalated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("initial_routing", "Initial Routing"),
                            ("no_response_timeout", "No Response Timeout"),
                            ("priest_declined", "Priest Declined"),
                            ("priest_unavailable", "Priest Unavailable"),
                            ("manual_admin_escalation", "Manual Admin Escalation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "escalated_to_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalated_to_priest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_received",
                        to="clergy.priestprofile",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="requests_app.sacramentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-escalated_at"],
            },
        ),
    ]
