# Generated by Django 5.0.14 on 2026-07-13 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("dioceses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diocesanadminprofile",
            name="diocese",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin_profiles",
                to="dioceses.diocese",
            ),
        ),
        migrations.AddField(
            model_name="diocesanadminprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diocesan_admin_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
