# Generated by Django 5.0.14 on 2026-07-13 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clergy", "0001_initial"),
        ("dioceses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="priestprofile",
            name="diocese",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="priests",
                to="dioceses.diocese",
            ),
        ),
        migrations.AddField(
            model_name="priestprofile",
            name="parish",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable at signup; required once verified.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="priests",
                to="dioceses.parish",
            ),
        ),
        migrations.AddField(
            model_name="priestprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priest_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="priestprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="priest_verifications_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="priestverificationevent",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="priestverificationevent",
            name="priest_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_events",
                to="clergy.priestprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="priestprofile",
            index=models.Index(fields=["current_location"], name="priest_location_gix"),
        ),
    ]
