# Generated by Django 5.0.14 on 2026-07-13 09:31

import apps.clergy.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clergy", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priestprofile",
            name="parish_attestation_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="clergy/attestations/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "jpg", "jpeg", "png")
                    ),
                    apps.clergy.validators.validate_attestation_document_size,
                ],
            ),
        ),
    ]
