# Generated by Django 5.0.14 on 2026-07-13 06:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clergy", "0002_initial"),
        ("dioceses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SacramentRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("requester_name", models.CharField(max_length=200)),
                ("requester_phone", models.CharField(max_length=20)),
                ("patient_name", models.CharField(max_length=200)),
                (
                    "sacrament_type",
                    models.CharField(
                        choices=[
                            ("confession", "Confession"),
                            ("communion_for_sick", "Holy Communion for the Sick"),
                            ("anointing_of_the_sick", "Anointing of the Sick"),
                            ("last_rites", "Last Rites"),
                            ("spiritual_counselling", "Spiritual Counselling"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "emergency_level",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            (
                                "emergency_danger_of_death",
                                "Emergency - Danger of Death",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "location_description",
                    models.TextField(
                        blank=True,
                        help_text="Free text landmark description, critical for rural/USSD cases.",
                    ),
                ),
                ("address_text", models.CharField(blank=True, max_length=255)),
                (
                    "hospital_or_home",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("home", "Home"),
                            ("care_facility", "Care Facility"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("family_contact_name", models.CharField(blank=True, max_length=200)),
                ("family_contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("routed", "Routed"),
                            ("accepted", "Accepted"),
                            ("en_route", "En Route"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("mobile_app", "Mobile App"),
                            ("ussd", "USSD"),
                            ("phone_call_manual_entry", "Phone Call (Manual Entry)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("logistics_notes", models.TextField(blank=True, max_length=1000)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_parish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routed_requests",
                        to="dioceses.parish",
                    ),
                ),
                (
                    "assigned_priest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to="clergy.priestprofile",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sacrament_requests",
                        to="dioceses.institution",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sacrament_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("submitted", "Submitted"),
                            ("routed", "Routed"),
                            ("accepted", "Accepted"),
                            ("en_route", "En Route"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("routed", "Routed"),
                            ("accepted", "Accepted"),
                            ("en_route", "En Route"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="requests_app.sacramentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sacramentrequest",
            index=models.Index(fields=["location"], name="request_location_gix"),
        ),
        migrations.AddIndex(
            model_name="sacramentrequest",
            index=models.Index(
                fields=["status", "emergency_level"], name="request_status_emerg_idx"
            ),
        ),
    ]
