# Generated by Django 5.0.14 on 2026-07-13 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("push", "Push"), ("email", "Email")],
                        max_length=10,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            (
                                "request_submitted_ack",
                                "Request Submitted Acknowledgement",
                            ),
                            ("priest_new_request_alert", "New Request Alert to Priest"),
                            (
                                "request_accepted_confirmation",
                                "Request Accepted Confirmation",
                            ),
                            ("escalation_alert", "Escalation Alert"),
                            ("status_update", "Status Update"),
                            ("verification_decision", "Verification Decision"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=100)),
                ("payload_summary", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
